token:
  expiration_time: 1111111111
  secret: userTokenSECRETCREATEBYtlrruaddbsuserTokenSECRETCREATEBYtlrrudddbsuserTokenSECRETCREATEBYtlreruddbsuserTokenSECRETCREATEBYtlrrudddbsKINMOMO
gateway:
  ip: 192.168.0.114
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: '{cipher}e4c0c6cb094135bcf3ab849f30bb1232f5b0eec28008190e207936609239c08d'