token:
  expiration_time: 2222222223
  secret: userTokenSECRETCREATEBYtlrruaddbsuserTokenSECRETCREATEBYtlrrudddbsuserTokenSECRETCREATEBYtlreruddbsuserTokenSECRETCREATEBYtlrrudddbsDEVUPDATE
gateway:
  ip: 192.168.0.114
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: '{cipher}59017163e0bcbab29c11d73998a44938ed52a0d89d1ea84698f441d6064822361'